apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  url: https://domen.example.uz

  accounts.rustam: apiKey, login
  accounts.rustam.enabled: "true"
  # ----------------------------
  # можно добавить нового пользователя, пример rustam,
  # которого добавил
  # ----------------------------
  accounts.user2: apiKey, login
  accounts.user2.enabled: "false"


  repositories: |
    - type: git
      url: https://github.com/rsdevops12/
